/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const DrawerForm: typeof import('./components/DrawerForm/index')['DrawerForm']
  const DrawerFormPlugin: typeof import('./components/DrawerForm/index')['DrawerFormPlugin']
  const EffectScope: typeof import('vue')['EffectScope']
  const LinkDiagram: typeof import('./components/LinkDiagram/index')['LinkDiagram']
  const LinkDiagramPlugin: typeof import('./components/LinkDiagram/index')['LinkDiagramPlugin']
  const LiteFilter: typeof import('./components/LiteFilter/index')['LiteFilter']
  const LiteFilterPlugin: typeof import('./components/LiteFilter/index')['LiteFilterPlugin']
  const LoginForm: typeof import('./components/LoginForm/index')['LoginForm']
  const ModalForm: typeof import('./components/ModalForm/index')['ModalForm']
  const ModalFormPlugin: typeof import('./components/ModalForm/index')['ModalFormPlugin']
  const NaiveProvider: typeof import('./components/NaiveProvider/index')['NaiveProvider']
  const NaiveProviderPlugin: typeof import('./components/NaiveProvider/index')['NaiveProviderPlugin']
  const ProDescriptions: typeof import('./components/ProDescriptions/index')['ProDescriptions']
  const ProDescriptionsPlugin: typeof import('./components/ProDescriptions/index')['ProDescriptionsPlugin']
  const ProForm: typeof import('./components/ProForm/index')['ProForm']
  const ProFormPlugin: typeof import('./components/ProForm/index')['ProFormPlugin']
  const ProLayout: typeof import('./components/ProLayout/index')['ProLayout']
  const ProLayoutPlugin: typeof import('./components/ProLayout/index')['ProLayoutPlugin']
  const ProList: typeof import('./components/ProList/index')['ProList']
  const ProListPlugin: typeof import('./components/ProList/index')['ProListPlugin']
  const ProTable: typeof import('./components/ProTable/index')['ProTable']
  const ProTablePlugin: typeof import('./components/ProTable/index')['ProTablePlugin']
  const ProText: typeof import('./components/ProText/index')['ProText']
  const ProTextPlugin: typeof import('./components/ProText/index')['ProTextPlugin']
  const QueryFilter: typeof import('./components/QueryFilter/index')['QueryFilter']
  const QueryFilterPlugin: typeof import('./components/QueryFilter/index')['QueryFilterPlugin']
  const Watermark: typeof import('./components/Watermark/index')['Watermark']
  const WatermarkPlugin: typeof import('./components/Watermark/index')['WatermarkPlugin']
  const computed: typeof import('vue')['computed']
  const createApp: typeof import('vue')['createApp']
  const customRef: typeof import('vue')['customRef']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const effectScope: typeof import('vue')['effectScope']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const h: typeof import('vue')['h']
  const inject: typeof import('vue')['inject']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const provide: typeof import('vue')['provide']
  const reactive: typeof import('vue')['reactive']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const textProps: typeof import('./components/ProText/src/types')['textProps']
  const toRaw: typeof import('vue')['toRaw']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const triggerRef: typeof import('vue')['triggerRef']
  const unref: typeof import('vue')['unref']
  const useAttrs: typeof import('vue')['useAttrs']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVars: typeof import('vue')['useCssVars']
  const useDialog: typeof import('naive-ui')['useDialog']
  const useId: typeof import('vue')['useId']
  const useLoadingBar: typeof import('naive-ui')['useLoadingBar']
  const useMessage: typeof import('naive-ui')['useMessage']
  const useModel: typeof import('vue')['useModel']
  const useNotification: typeof import('naive-ui')['useNotification']
  const useShowSuffix: typeof import('./hooks/useShowSuffix')['useShowSuffix']
  const useSlots: typeof import('vue')['useSlots']
  const useTableColumns: typeof import('./hooks/useTableColumns')['useTableColumns']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { ProTextProps } from './components/ProText/src/types'
  import('./components/ProText/src/types')
  // @ts-ignore
  export type { FormConfig, QueryFilterColumn, QueryFilterProps } from './components/QueryFilter/src/types'
  import('./components/QueryFilter/src/types')
  // @ts-ignore
  export type { WatermarkProps } from './components/Watermark/src/types'
  import('./components/Watermark/src/types')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly DrawerForm: UnwrapRef<typeof import('./components/DrawerForm/index')['DrawerForm']>
    readonly DrawerFormPlugin: UnwrapRef<typeof import('./components/DrawerForm/index')['DrawerFormPlugin']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly LinkDiagram: UnwrapRef<typeof import('./components/LinkDiagram/index')['LinkDiagram']>
    readonly LinkDiagramPlugin: UnwrapRef<typeof import('./components/LinkDiagram/index')['LinkDiagramPlugin']>
    readonly LiteFilter: UnwrapRef<typeof import('./components/LiteFilter/index')['LiteFilter']>
    readonly LiteFilterPlugin: UnwrapRef<typeof import('./components/LiteFilter/index')['LiteFilterPlugin']>
    readonly LoginForm: UnwrapRef<typeof import('./components/LoginForm/index')['LoginForm']>
    readonly ModalForm: UnwrapRef<typeof import('./components/ModalForm/index')['ModalForm']>
    readonly ModalFormPlugin: UnwrapRef<typeof import('./components/ModalForm/index')['ModalFormPlugin']>
    readonly NaiveProvider: UnwrapRef<typeof import('./components/NaiveProvider/index')['NaiveProvider']>
    readonly NaiveProviderPlugin: UnwrapRef<typeof import('./components/NaiveProvider/index')['NaiveProviderPlugin']>
    readonly ProDescriptions: UnwrapRef<typeof import('./components/ProDescriptions/index')['ProDescriptions']>
    readonly ProDescriptionsPlugin: UnwrapRef<typeof import('./components/ProDescriptions/index')['ProDescriptionsPlugin']>
    readonly ProForm: UnwrapRef<typeof import('./components/ProForm/index')['ProForm']>
    readonly ProFormPlugin: UnwrapRef<typeof import('./components/ProForm/index')['ProFormPlugin']>
    readonly ProLayout: UnwrapRef<typeof import('./components/ProLayout/index')['ProLayout']>
    readonly ProLayoutPlugin: UnwrapRef<typeof import('./components/ProLayout/index')['ProLayoutPlugin']>
    readonly ProList: UnwrapRef<typeof import('./components/ProList/index')['ProList']>
    readonly ProListPlugin: UnwrapRef<typeof import('./components/ProList/index')['ProListPlugin']>
    readonly ProTable: UnwrapRef<typeof import('./components/ProTable/index')['ProTable']>
    readonly ProTablePlugin: UnwrapRef<typeof import('./components/ProTable/index')['ProTablePlugin']>
    readonly ProText: UnwrapRef<typeof import('./components/ProText/index')['ProText']>
    readonly ProTextPlugin: UnwrapRef<typeof import('./components/ProText/index')['ProTextPlugin']>
    readonly QueryFilter: UnwrapRef<typeof import('./components/QueryFilter/index')['QueryFilter']>
    readonly QueryFilterPlugin: UnwrapRef<typeof import('./components/QueryFilter/index')['QueryFilterPlugin']>
    readonly Watermark: UnwrapRef<typeof import('./components/Watermark/index')['Watermark']>
    readonly WatermarkPlugin: UnwrapRef<typeof import('./components/Watermark/index')['WatermarkPlugin']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly textProps: UnwrapRef<typeof import('./components/ProText/src/types')['textProps']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDialog: UnwrapRef<typeof import('naive-ui')['useDialog']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useLoadingBar: UnwrapRef<typeof import('naive-ui')['useLoadingBar']>
    readonly useMessage: UnwrapRef<typeof import('naive-ui')['useMessage']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useNotification: UnwrapRef<typeof import('naive-ui')['useNotification']>
    readonly useShowSuffix: UnwrapRef<typeof import('./hooks/useShowSuffix')['useShowSuffix']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useTableColumns: UnwrapRef<typeof import('./hooks/useTableColumns')['useTableColumns']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}