/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LoginCard: typeof import('./components/LoginForm/src/components/LoginCard.vue')['default']
    LoginImage: typeof import('./components/LoginForm/src/components/LoginImage.vue')['default']
    PrivacyPolicy: typeof import('./components/LoginForm/src/components/PrivacyPolicy.vue')['default']
    SignUpLink: typeof import('./components/LoginForm/src/components/SignUpLink.vue')['default']
    Src: typeof import('./components/LoginForm/src/index.vue')['default']
  }
}
