/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/docs/-v/': RouteRecordInfo<'/docs/-v/', '/docs/-v', Record<never, never>, Record<never, never>>,
    '/docs/-v/getting-started': RouteRecordInfo<'/docs/-v/getting-started', '/docs/-v/getting-started', Record<never, never>, Record<never, never>>,
    '/docs/-v/introduce': RouteRecordInfo<'/docs/-v/introduce', '/docs/-v/introduce', Record<never, never>, Record<never, never>>,
    '/docs/ks/': RouteRecordInfo<'/docs/ks/', '/docs/ks', Record<never, never>, Record<never, never>>,
    '/docs/ks/base': RouteRecordInfo<'/docs/ks/base', '/docs/ks/base', Record<never, never>, Record<never, never>>,
    '/docs/ks/login': RouteRecordInfo<'/docs/ks/login', '/docs/ks/login', Record<never, never>, Record<never, never>>,
    '/docs/omponent/': RouteRecordInfo<'/docs/omponent/', '/docs/omponent', Record<never, never>, Record<never, never>>,
    '/docs/omponent/drawer-form': RouteRecordInfo<'/docs/omponent/drawer-form', '/docs/omponent/drawer-form', Record<never, never>, Record<never, never>>,
    '/docs/omponent/faq': RouteRecordInfo<'/docs/omponent/faq', '/docs/omponent/faq', Record<never, never>, Record<never, never>>,
    '/docs/omponent/getting-started': RouteRecordInfo<'/docs/omponent/getting-started', '/docs/omponent/getting-started', Record<never, never>, Record<never, never>>,
    '/docs/omponent/modal-form': RouteRecordInfo<'/docs/omponent/modal-form', '/docs/omponent/modal-form', Record<never, never>, Record<never, never>>,
    '/docs/omponent/pro-descriptions': RouteRecordInfo<'/docs/omponent/pro-descriptions', '/docs/omponent/pro-descriptions', Record<never, never>, Record<never, never>>,
    '/docs/omponent/pro-form': RouteRecordInfo<'/docs/omponent/pro-form', '/docs/omponent/pro-form', Record<never, never>, Record<never, never>>,
    '/docs/omponent/pro-layout': RouteRecordInfo<'/docs/omponent/pro-layout', '/docs/omponent/pro-layout', Record<never, never>, Record<never, never>>,
    '/docs/omponent/pro-list': RouteRecordInfo<'/docs/omponent/pro-list', '/docs/omponent/pro-list', Record<never, never>, Record<never, never>>,
    '/docs/omponent/pro-table': RouteRecordInfo<'/docs/omponent/pro-table', '/docs/omponent/pro-table', Record<never, never>, Record<never, never>>,
    '/docs/omponent/pro-text': RouteRecordInfo<'/docs/omponent/pro-text', '/docs/omponent/pro-text', Record<never, never>, Record<never, never>>,
    '/docs/omponent/tour': RouteRecordInfo<'/docs/omponent/tour', '/docs/omponent/tour', Record<never, never>, Record<never, never>>,
    '/docs/omponent/watermark': RouteRecordInfo<'/docs/omponent/watermark', '/docs/omponent/watermark', Record<never, never>, Record<never, never>>,
    '/docs/s/': RouteRecordInfo<'/docs/s/', '/docs/s', Record<never, never>, Record<never, never>>,
    '/docs/s/base': RouteRecordInfo<'/docs/s/base', '/docs/s/base', Record<never, never>, Record<never, never>>,
    '/docs/x': RouteRecordInfo<'/docs/x', '/docs/x', Record<never, never>, Record<never, never>>,
  }
}
