/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/datav/': RouteRecordInfo<'/datav/', '/datav', Record<never, never>, Record<never, never>>,
    '/datav/bar_line': RouteRecordInfo<'/datav/bar_line', '/datav/bar_line', Record<never, never>, Record<never, never>>,
    '/datav/circle_bar': RouteRecordInfo<'/datav/circle_bar', '/datav/circle_bar', Record<never, never>, Record<never, never>>,
    '/datav/cube_bar': RouteRecordInfo<'/datav/cube_bar', '/datav/cube_bar', Record<never, never>, Record<never, never>>,
    '/datav/pie': RouteRecordInfo<'/datav/pie', '/datav/pie', Record<never, never>, Record<never, never>>,
    '/docs/en/': RouteRecordInfo<'/docs/en/', '/docs/en', Record<never, never>, Record<never, never>>,
    '/docs/overview': RouteRecordInfo<'/docs/overview', '/docs/overview', Record<never, never>, Record<never, never>>,
    '/docs/zh/': RouteRecordInfo<'/docs/zh/', '/docs/zh', Record<never, never>, Record<never, never>>,
    '/error': RouteRecordInfo<'/error', '/error', Record<never, never>, Record<never, never>>,
    '/procomponent/': RouteRecordInfo<'/procomponent/', '/procomponent', Record<never, never>, Record<never, never>>,
    '/procomponent/naive-provider': RouteRecordInfo<'/procomponent/naive-provider', '/procomponent/naive-provider', Record<never, never>, Record<never, never>>,
    '/procomponent/overview': RouteRecordInfo<'/procomponent/overview', '/procomponent/overview', Record<never, never>, Record<never, never>>,
    '/procomponent/pro-descriptions': RouteRecordInfo<'/procomponent/pro-descriptions', '/procomponent/pro-descriptions', Record<never, never>, Record<never, never>>,
    '/procomponent/pro-form': RouteRecordInfo<'/procomponent/pro-form', '/procomponent/pro-form', Record<never, never>, Record<never, never>>,
    '/procomponent/pro-layout': RouteRecordInfo<'/procomponent/pro-layout', '/procomponent/pro-layout', Record<never, never>, Record<never, never>>,
    '/procomponent/pro-table': RouteRecordInfo<'/procomponent/pro-table', '/procomponent/pro-table', Record<never, never>, Record<never, never>>,
    '/procomponent/pro-text': RouteRecordInfo<'/procomponent/pro-text', '/procomponent/pro-text', Record<never, never>, Record<never, never>>,
    '/procomponent/watermark': RouteRecordInfo<'/procomponent/watermark', '/procomponent/watermark', Record<never, never>, Record<never, never>>,
  }
}
